production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

  AWS_S3_BUCKET_NAME: "okeassetbkt"
  AWS_ACCESS_KEY_ID: "AKIAIGACPCFRCJ3QE6BQ"
  AWS_SECRET_ACCESS_KEY: "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"


